server:
    port: 8084
    tomcat:
          max-threads: 1000
          uri-encoding: UTF-8

spring:
    datasource:
        url: jdbc:mysql://rm-uf6977kr359gdqk3v.mysql.rds.aliyuncs.com:3306/hkd_pro?useUnicode=true&characterEncoding=UTF-8
        username: xjdrds
        password: xjd@2017
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        cluster:
          nodes:
            - 172.17.40.13:7000
            - 172.17.40.13:7001
            - 172.17.40.14:7002
            - 172.17.40.14:7003
            - 172.17.40.15:7004
            - 172.17.40.15:7005
#        password:
    mvc:
            view:
              prefix: /WEB-INF/
              suffix: .jsp

# 日志
logging:
    config: classpath:logback.xml
#swagger开关
swagger:
    enable: true
#七牛云
domainOfBucket: f.hengkuaidai.com

#测试地址
#serverUrl: https://openapi.qiyuesuo.me
##测试accessKey
#accessKey: pI3VlifaYs
##测试accessSecret
#accessSecret: QkzsaNLjXttwrLpJFsv6MLAIFj6cEH


#正式地址
serverUrl: https://openapi.qiyuesuo.com
#正式accessKey
accessKey: Hbn9wt5P2j
#正式accessSecret
accessSecret: 32jE2KpXHg9gnuy4p06BGluDLGVx92