server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8084

spring:
    datasource:
        url: jdbc:mysql://116.62.146.185:3306/hkd_test?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: huoxinjihuatest
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        cluster:
          nodes:
            - 172.16.243.67:7000
            - 172.16.243.67:7001
            - 172.16.243.67:7002
            - 172.16.243.67:7003
            - 172.16.243.67:7004
            - 172.16.243.67:7005
        password: redispassword
    mvc:
            view:
              prefix: /WEB-INF/
              suffix: .jsp

# 日志
logging:
    config: classpath:logback.xml
#swagger开关
swagger:
   enable: true
#七牛云
domainOfBucket: f.hengkuaidai.com

#契约锁
#测试地址
#serverUrl: https://openapi.qiyuesuo.me
##测试accessKey
#accessKey: pI3VlifaYs
##测试accessSecret
#accessSecret: QkzsaNLjXttwrLpJFsv6MLAIFj6cEH


#正式地址
serverUrl: https://openapi.qiyuesuo.com
#正式accessKey
accessKey: Hbn9wt5P2j
#正式accessSecret
accessSecret: 32jE2KpXHg9gnuy4p06BGluDLGVx92
