server:
    port: 8084

spring:
    datasource:
        url: jdbc:mysql://116.62.146.185:3306/hkd_test?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: huoxinjihuatest
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      cluster:
        nodes:
          - 172.16.243.67:7000
          - 172.16.243.67:7001
          - 172.16.243.67:7002
          - 172.16.243.67:7003
          - 172.16.243.67:7004
          - 172.16.243.67:7005


